apiVersion: v2
appVersion: r2020b
description: Mathworks Matlab chart
name: matlab
version: 0.0.2
kubeVersion: ">=1.16.0-0"
home: https://github.com/sennerholm/nvidia-charts/charts/tree/master/charts/matlab
maintainers:
- name: Mikael Sennerholm
  email: mikael@sennerholm.net
dependencies:
- name: common
  repository: https://k8s-at-home.com/charts/
  version: 3.0.1